In [67]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


In [68]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [69]:
df.shape

(569, 33)

In [70]:
df.describe()

id  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000   
mean   3.037183e+07    14.127292     19.289649       91.969033   654.889104   
std    1.250206e+08     3.524049      4.301036       24.298981   351.914129   
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000   
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000   
50%    9.060240e+05    13.370000     18.840000       86.240000   551.100000   
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000   
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean  ...  texture_worst  perimeter_worst   area_worst  \
count     569.000000  ...     569.000000       569.000000   569.000000   
mean        0.181162  ...      25.677223       107.261213   880.583128   
std         0.027414  ...       6.146258        33.602542   569.356993   
min         0.106000  ...      12.020000        50.410000   185.200000   
25%         0.161900  ...      21.080000        84.110000   515.300000   
50%         0.179200  ...      25.410000        97.660000   686.500000   
75%         0.195700  ...      29.720000       125.400000  1084.000000   
max         0.304000  ...      49.540000       251.200000  4254.000000   

       smoothness_worst  compactness_worst  concavity_worst  \
count        569.000000         569.000000       569.000000   
mean           0.132369           0.254265         0.272188   
std            0.022832           0.157336         0.208624   
min            0.071170           0.027290         0.000000   
25%            0.116600           0.147200         0.114500   
50%            0.131300           0.211900         0.226700   
75%            0.146000           0.339100         0.382900   
max            0.222600           1.058000         1.252000   

       concave points_worst  symmetry_worst  fractal_dimension_worst  \
count            569.000000      569.000000               569.000000   
mean               0.114606        0.290076                 0.083946   
std                0.065732        0.061867                 0.018061   
min                0.000000        0.156500                 0.055040   
25%                0.064930        0.250400                 0.071460   
50%                0.099930        0.282200                 0.080040   
75%                0.161400        0.317900                 0.092080   
max                0.291000        0.663800                 0.207500   

       Unnamed: 32  
count          0.0  
mean           NaN  
std            NaN  
min            NaN  
25%            NaN  
50%            NaN  
75%            NaN  
max            NaN  

[8 rows x 32 columns]

In [71]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [72]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

***train ntest split***

In [73]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [74]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [75]:
X_train

array([[-0.48713831, -0.67057995, -0.38241423, ...,  0.29451793,
         0.5044307 ,  1.13194889],
       [ 0.38852881, -1.71939222,  0.44668036, ...,  1.03295362,
         0.48064732,  0.99370301],
       [-0.45513718, -0.05335857, -0.42165382, ..., -0.33810068,
        -1.2555395 , -0.6836803 ],
       ...,
       [ 1.01109613,  0.9351238 ,  1.14286665, ...,  1.2902642 ,
        -0.97013893,  2.22639542],
       [-0.35913381, -1.20426761, -0.2938087 , ...,  0.6279559 ,
        -0.43422007,  1.96142415],
       [-0.84496906,  0.12995154, -0.84274104, ..., -1.44088206,
         0.60114979, -1.06731261]])

In [76]:
y_train

485    B
172    M
355    B
443    B
394    B
      ..
453    B
255    M
468    M
247    B
332    B
Name: diagnosis, Length: 455, dtype: object

**Label Encoding**

In [77]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [78]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,

**Numpy arrays to PyTorch tensors**

In [79]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [80]:
X_train_tensor.shape

torch.Size([455, 30])

In [81]:
y_train_tensor.shape

torch.Size([455])

**Defining the model**

In [82]:
class MySimpleNN():

  def  __init__(self,X):
    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.rand(1,dtype=torch.float64,requires_grad=True)
  def forward(self,X):
    z=torch.matmul(X,self.weights)+self.bias
    y_pred= torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss



In [83]:
learning_rate=0.24
epochs=25

In [87]:
model=MySimpleNN(X_train_tensor)
model.weights

tensor([[0.8451],
        [0.4235],
        [0.0170],
        [0.5933],
        [0.0175],
        [0.6342],
        [0.2139],
        [0.7676],
        [0.8918],
        [0.5164],
        [0.4955],
        [0.2119],
        [0.6999],
        [0.1153],
        [0.0348],
        [0.0238],
        [0.1301],
        [0.1052],
        [0.9681],
        [0.0057],
        [0.3408],
        [0.7383],
        [0.7960],
        [0.5952],
        [0.9715],
        [0.3681],
        [0.2620],
        [0.1862],
        [0.1685],
        [0.3418]], dtype=torch.float64, requires_grad=True)

In [84]:
# create model
model=MySimpleNN(X_train_tensor)
#define loop
for epoch in range(epochs):
#forward prop
  y_pred=model.forward(X_train_tensor)

#loss calculate
  loss=model.loss_function(y_pred,y_train_tensor)

#backward propagation
  loss.backward()
   # parameters update
  with torch.no_grad():# no need to track gradients while updating params
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad


  # zero gradients at every end of epoch grad should be 0 ,so tht it doesn't accumulate for next epoch and get added
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.667727770628545
Epoch: 2, Loss: 3.353119328989698
Epoch: 3, Loss: 3.0161643934754205
Epoch: 4, Loss: 2.6336146161798974
Epoch: 5, Loss: 2.2204519832097955
Epoch: 6, Loss: 1.804252926854413
Epoch: 7, Loss: 1.418837963497637
Epoch: 8, Loss: 1.1019812470074817
Epoch: 9, Loss: 0.9047708347527575
Epoch: 10, Loss: 0.8170084765392229
Epoch: 11, Loss: 0.7847750716042059
Epoch: 12, Loss: 0.7674444233325822
Epoch: 13, Loss: 0.7538283902130957
Epoch: 14, Loss: 0.7421563916456226
Epoch: 15, Loss: 0.7320498101899948
Epoch: 16, Loss: 0.7232934162038397
Epoch: 17, Loss: 0.715704695663652
Epoch: 18, Loss: 0.7091223286583149
Epoch: 19, Loss: 0.703404916598199
Epoch: 20, Loss: 0.6984298750474661
Epoch: 21, Loss: 0.6940918546925982
Epoch: 22, Loss: 0.6903008721857998
Epoch: 23, Loss: 0.6869803582213785
Epoch: 24, Loss: 0.6840652732819352
Epoch: 25, Loss: 0.6815003812828851


In [86]:
model.weights

tensor([[ 0.4715],
        [-0.0659],
        [-0.3796],
        [ 0.4074],
        [ 0.1192],
        [ 0.0335],
        [ 0.0640],
        [ 0.1344],
        [-0.2134],
        [-0.0588],
        [-0.0740],
        [ 0.0448],
        [-0.1968],
        [ 0.3345],
        [-0.0165],
        [ 0.2619],
        [ 0.0135],
        [-0.0422],
        [ 0.0292],
        [-0.1276],
        [-0.3240],
        [ 0.0542],
        [-0.1549],
        [-0.2234],
        [ 0.1412],
        [-0.0566],
        [-0.0345],
        [-0.1125],
        [ 0.1701],
        [-0.1214]], dtype=torch.float64, requires_grad=True)

In [85]:
model.bias

tensor([-0.2206], dtype=torch.float64, requires_grad=True)

In [89]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5152354836463928
