Arithmetic operations, broadcasting and comparison
Numpy arrays support arithmetic operators like +, -, *, etc. You can perform an arithmetic operation with a single number (also called scalar) or with another array of the same shape. Operators make it easy to write mathematical expressions with multi-dimensional arrays.

In [1]:
import numpy as np
import pandas as pd

In [2]:
arr1=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

In [3]:
arr2=np.array([[11,12,13,14],
               [15,16,17,18],
               [19,20,21,22]])

In [4]:
arr1+arr2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [5]:
arr1-arr2

array([[-10, -10, -10, -10],
       [-10, -10, -10, -10],
       [-10, -10, -10, -10]])

In [6]:
arr2/2

array([[ 5.5,  6. ,  6.5,  7. ],
       [ 7.5,  8. ,  8.5,  9. ],
       [ 9.5, 10. , 10.5, 11. ]])

In [7]:
arr1*arr2

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171, 200, 231, 264]])

In [8]:
arr2%4

array([[3, 0, 1, 2],
       [3, 0, 1, 2],
       [3, 0, 1, 2]])

**Array Broadcasting
Numpy arrays also support broadcasting, allowing arithmetic operations between two arrays with different numbers of dimensions but compatible shapes. Let's look at an example to see how it works**

In [9]:
arr2=np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])

In [10]:
arr2.shape

(3, 4)

In [11]:
arr4=np.array([2,4,6,8])

In [12]:
arr4.shape

(4,)

In [13]:
arr2+arr4

array([[ 3,  6,  9, 12],
       [ 7, 10, 13, 16],
       [11, 14, 17, 20]])

When the expression arr2 + arr4 is evaluated, arr4 (which has the shape (4,)) is replicated three times to match the shape (3, 4) of arr2. Numpy performs the replication without actually creating three copies of the smaller dimension array, thus improving performance and using lower memory.

In [14]:
arr4_replicated=np.array([[2,4,6,8],
                          [2,4,6,8],
                          [2,4,6,8]])

In [15]:
arr2+arr4_replicated

array([[ 3,  6,  9, 12],
       [ 7, 10, 13, 16],
       [11, 14, 17, 20]])

In [16]:
arr5 = np.array([7, 8])

In [17]:
arr2 + arr5

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

In the above example, even if arr5 is replicated three times, it will not match the shape of arr2. Hence arr2 + arr5 cannot be evaluated successfully. Learn more about broadcasting here:



---



Array Comparison
Numpy arrays also support comparison operations like ==, !=, > etc. The result is an array of booleans.

In [18]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

In [19]:
arr1==arr2

array([[False,  True,  True],
       [False, False,  True]])

In [20]:
arr1!=arr2

array([[ True, False, False],
       [ True,  True, False]])

In [21]:
arr1>arr2

array([[False, False, False],
       [ True,  True, False]])

In [22]:
(arr1==arr2).dtype

dtype('bool')

In [23]:
(arr1==arr2).sum()

np.int64(3)

Array indexing and slicing
Numpy extends Python's list indexing notation using [] to multiple dimensions in an intuitive fashion. You can provide a comma-separated list of indices or ranges to select a specific element or a subarray (also called a slice) from a Numpy array.

In [24]:
arr3=np.array([[[11,12,13,14],
                [15,16,17,18]],
               [[19,20,21,22],
               [23,24,25,26]],
               [[27,28,29,30],
                [31,31,33,34]]])

In [25]:
arr3.shape

(3, 2, 4)

In [28]:
arr3[0,1,1]

np.int64(16)

In [33]:
arr3[1:,0:1,:2]

array([[[19, 20]],

       [[27, 28]]])

In [34]:
# Mixing indices and ranges
arr3[1:, 1, 3]

array([26, 34])

In [35]:
# Mixing indices and ranges
arr3[1:, 1, :3]

array([[23, 24, 25],
       [31, 31, 33]])

In [36]:
# Using fewer indices
arr3[1]

array([[19, 20, 21, 22],
       [23, 24, 25, 26]])

In [37]:
# Using fewer indices
arr3[:2, 1]

array([[15, 16, 17, 18],
       [23, 24, 25, 26]])

Other ways of creating Numpy arrays
Numpy also provides some handy functions to create arrays of desired shapes with fixed or random values. Check out the official documentation or use the help function to learn more.

In [38]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [39]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
# Random vector
np.random.rand(5)

array([0.71402744, 0.46239845, 0.54271445, 0.17249576, 0.50181453])

In [42]:
# Random matrix
np.random.randn(2, 3) # rand vs. randn - what's the difference?

array([[-0.35717232,  0.86358883, -0.65790773],
       [ 0.29157957, -0.90097835,  1.714884  ]])

randn gives the value fromm normal distribution, rand gives between 0-1

In [43]:
np.full((2,3),23)

array([[23, 23, 23],
       [23, 23, 23]])

In [44]:
np.arange(10,90,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [47]:
np.linspace(3,27,9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])