In [87]:
import torch
print(torch.__version__)


2.6.0+cu124


In [88]:
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))

**CREATING TENSOR**

In [89]:
#using empty ranom indialization ,values not in a specific range , random garbage values assigned
a=torch.empty(2,3)

In [90]:
#using type
type(a)

torch.Tensor

In [91]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [92]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [93]:
#using randonm, rnage if intialization , bewtween 0 and 1
torch.rand(2,3)

tensor([[0.9556, 0.9761, 0.5934],
        [0.3124, 0.9431, 0.8519]])

In [94]:
torch.rand(2,3)

tensor([[0.9815, 0.1132, 0.4783],
        [0.4436, 0.3847, 0.4521]])

In [95]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [96]:
torch.manual_seed(100)#it will be same elemnts after manual seeding
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [97]:
torch.tensor([[1,2,3],[7,8,9]])

tensor([[1, 2, 3],
        [7, 8, 9]])

In [98]:
#OTHER WAYS
print( "Using arange:->" ,torch.arange(0,10))
print("Using arange:->",torch.arange(0,10,2))
print("Using linspace:->",torch.linspace(0,10,10))#evenly spaced 10 values between 0 and 10
print("Using eye:->",torch.eye(5))
print("Using full:->",torch.full((3,3),5))
#

Using arange:-> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Using arange:-> tensor([0, 2, 4, 6, 8])
Using linspace:-> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eye:-> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full:-> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


**TENSOR SHAPES**

In [99]:
x=torch.tensor([[1,2,3],[5,6,7]])

In [100]:
x.shape

torch.Size([2, 3])

In [101]:
torch.empty_like(x)

tensor([[        153873072,         156816064, 72340172838076673],
        [        536870913,                48,                48]])

In [102]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [103]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [104]:
#torch.rand_like(x)# it gives error because rand will give float values but x has int values  this will be solved in later section

**TENSOR DATA TYPES**

In [105]:
x.dtype

torch.int64

In [106]:
#assigning dtype
torch.tensor([1.9,2.3,3.4],dtype=torch.int32)


tensor([1, 2, 3], dtype=torch.int32)

In [107]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [108]:
torch.rand_like(x,dtype=torch.float64)

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

**MATHEMATICAL OPERATONS ON TENSORS**

In [109]:
x=torch.rand(2,2)

In [110]:
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [111]:
#additon
x+2
#subtraction
x-2
#multiplication
x*3
#divison
x/3
#int division
x*100//3
#mod
(x*100//3)%2
#power
x**2


tensor([[0.0501, 0.0914],
        [0.0318, 0.6787]])

In [112]:
a=torch.rand(2,2)
b=torch.rand(2,2)
print(a)
print(b)

tensor([[0.5557, 0.9770],
        [0.4440, 0.9478]])
tensor([[0.7445, 0.4892],
        [0.2426, 0.7003]])


In [113]:
a+b
a-b
a*b
a/b
a**b
a%b
a//b

tensor([[0., 1.],
        [1., 1.]])

In [114]:
c=torch.tensor([1,-2,4,-8])

In [115]:
#for absoute value
torch.abs(c)

tensor([1, 2, 4, 8])

In [116]:
# changes sign of elemnet
torch.neg(c)

tensor([-1,  2, -4,  8])

In [117]:
d=torch.tensor([1,-2,3,4])

In [118]:
# rounding off
torch.round(d)

tensor([ 1, -2,  3,  4])

In [119]:
#ceil
torch.ceil(d)

tensor([ 1, -2,  3,  4])

In [120]:
#floor
torch.floor(d)

tensor([ 1, -2,  3,  4])

In [121]:
#IMPORTANT :CLAMP FN(putting all elements in range)
torch.clamp(d,min=1,max=3)

tensor([1, 1, 3, 3])

**REDUCTION OPERATION**

In [122]:
e=torch.randint(size=(2,3),low=0,high=10)

In [123]:
e

tensor([[7, 0, 0],
        [9, 5, 7]])

In [124]:
torch.sum(e)
torch.sum(e,dim=0)#sum along clumns
torch.sum(e,dim=1)#sum along rows

tensor([ 7, 21])

In [125]:
torch.mean(e.float())

tensor(4.6667)

In [126]:
torch.mean(e.float(),dim=0)#mean column wise

tensor([8.0000, 2.5000, 3.5000])

In [127]:
torch.median(e)

tensor(5)

In [128]:
torch.max(e)

tensor(9)

In [129]:
torch.min(e)

tensor(0)

In [130]:
#product
torch.prod(e)

tensor(0)

In [131]:
#std deviation
torch.std(e.float())

tensor(3.8297)

In [132]:
#variance
torch.var(e.float())

tensor(14.6667)

In [133]:
torch.argmax(e)

tensor(3)

In [134]:
torch.argmin(e)

tensor(1)

**MATRIX OPERATION**

In [135]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
f

tensor([[3, 9, 4],
        [0, 5, 7]])

In [136]:
g

tensor([[5, 9],
        [9, 7],
        [5, 9]])

In [137]:
torch.matmul(f,g)

tensor([[116, 126],
        [ 80,  98]])

In [138]:
vec1=torch.tensor([1,2])
vec2=torch.tensor([3,4])
torch.dot(vec1,vec2)

tensor(11)

In [139]:
f

tensor([[3, 9, 4],
        [0, 5, 7]])

In [140]:
#transpoose
torch.transpose(f,0,1)

tensor([[3, 0],
        [9, 5],
        [4, 7]])

In [141]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)

In [142]:
h

tensor([[8., 9., 7.],
        [9., 2., 6.],
        [7., 7., 8.]])

In [143]:
#determinant
torch.det(h)

tensor(-135.0000)

In [144]:
#inverse
torch.inverse(h)

tensor([[ 0.1926,  0.1704, -0.2963],
        [ 0.2222, -0.1111, -0.1111],
        [-0.3630, -0.0519,  0.4815]])

In [145]:
i=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
j=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
print(i)
print(j)

tensor([[3., 6., 1.],
        [5., 5., 0.],
        [4., 3., 8.]])
tensor([[8., 3., 3.],
        [5., 0., 6.],
        [4., 0., 8.]])


In [146]:
i>j
i<j
i==j
i!=j
i>=j
i<=j

tensor([[ True, False,  True],
        [ True, False,  True],
        [ True, False,  True]])

**SPECIAL FUNCTIONS**

In [147]:
k=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
k

tensor([[4., 7., 2.],
        [3., 8., 5.],
        [6., 2., 9.]])

In [148]:
#log
torch.log(k)

tensor([[1.3863, 1.9459, 0.6931],
        [1.0986, 2.0794, 1.6094],
        [1.7918, 0.6931, 2.1972]])

In [149]:
#sqrt
torch.sqrt(k)

tensor([[2.0000, 2.6458, 1.4142],
        [1.7321, 2.8284, 2.2361],
        [2.4495, 1.4142, 3.0000]])

In [150]:
#sigmoid
torch.sigmoid(k)

tensor([[0.9820, 0.9991, 0.8808],
        [0.9526, 0.9997, 0.9933],
        [0.9975, 0.8808, 0.9999]])

In [151]:
#softmax
torch.softmax(k,dim=0)

tensor([[1.1420e-01, 2.6845e-01, 8.9468e-04],
        [4.2010e-02, 7.2974e-01, 1.7970e-02],
        [8.4379e-01, 1.8088e-03, 9.8114e-01]])

In [152]:
#RELu
torch.relu(k)

tensor([[4., 7., 2.],
        [3., 8., 5.],
        [6., 2., 9.]])

**INPLACE OPERATIONS: put _ in front of functions it become inplace operation permanent changes**

In [153]:
m=torch.rand(2,3)
n=torch.rand(2,3)
print(m)
print(n)

tensor([[0.9516, 0.2855, 0.2324],
        [0.9141, 0.7668, 0.1659]])
tensor([[0.4393, 0.2243, 0.8935],
        [0.0497, 0.1780, 0.3011]])


In [154]:
m.add_(n)# this function adds m and n and ten puts the sum into m again

tensor([[1.3909, 0.5098, 1.1259],
        [0.9638, 0.9448, 0.4670]])

In [155]:
m #see the change in above m and this m

tensor([[1.3909, 0.5098, 1.1259],
        [0.9638, 0.9448, 0.4670]])

In [156]:
n#remains same

tensor([[0.4393, 0.2243, 0.8935],
        [0.0497, 0.1780, 0.3011]])

**COPYING A TENSOR**

In [157]:
a=torch.rand(2,3)
b=torch.rand(2,3)
a

tensor([[0.1893, 0.9186, 0.2131],
        [0.3957, 0.6017, 0.4234]])

In [158]:
b=a
b

tensor([[0.1893, 0.9186, 0.2131],
        [0.3957, 0.6017, 0.4234]])

In [160]:
a[0][0]=0
a

tensor([[0.0000, 0.9186, 0.2131],
        [0.3957, 0.6017, 0.4234]])

In [161]:
b# we can see b also changes when we are directly using '=' operator: WE WANT TO AVOID IT

tensor([[0.0000, 0.9186, 0.2131],
        [0.3957, 0.6017, 0.4234]])

In [162]:
id(a)

133462844868944

In [165]:
id(b)#same id as a: WE WANT TO AVOID IT

133462844868944

In [166]:
b=a.clone()

In [167]:
a[0][0]=10
a

tensor([[10.0000,  0.9186,  0.2131],
        [ 0.3957,  0.6017,  0.4234]])

In [168]:
b# differnet now

tensor([[0.0000, 0.9186, 0.2131],
        [0.3957, 0.6017, 0.4234]])

In [169]:
id(a)

133462844868944

In [170]:
id(b)#now differnt address

133462407491856

**Reshaping Tensors**

In [173]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [174]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [175]:
b=torch.rand(2,3,4)
b

tensor([[[0.8277, 0.6594, 0.0887, 0.4890],
         [0.5887, 0.7340, 0.8497, 0.9112],
         [0.4847, 0.9436, 0.3904, 0.2499]],

        [[0.3206, 0.9753, 0.7582, 0.6688],
         [0.2651, 0.2336, 0.5057, 0.5688],
         [0.0634, 0.8993, 0.2732, 0.3397]]])

In [178]:
#permute
b.permute(2,0,1).shape#interchange the row collumn position

torch.Size([4, 2, 3])

In [181]:
#unsqueezwe
#image size
c=torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [182]:
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [183]:
#squeeze
d=torch.rand(1,20)
d

tensor([[0.0289, 0.0433, 0.6532, 0.7963, 0.4182, 0.6831, 0.0971, 0.8091, 0.6566,
         0.6673, 0.9820, 0.8727, 0.6075, 0.8980, 0.6448, 0.4835, 0.3448, 0.5868,
         0.7389, 0.8681]])

In [184]:
d.squeeze(0).shape

torch.Size([20])

**NUMPY AND PyTorch**

In [185]:
import numpy as np

In [186]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [187]:
b=a.numpy()

In [188]:
b

array([1, 2, 3])

In [189]:
type(b)

numpy.ndarray

In [190]:
c=np.array([1,2,3])

In [191]:
torch.from_numpy(c)

tensor([1, 2, 3])